services:
  backend:
    build: ./Backend
    dockerfile: dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || curl -f http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
