name: CI

on:
  push:
    branches: [ main, JuanDev ]
  pull_request:
    branches: [ main, JuanDev ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/app/requirements.txt
          if [ -f Backend/app/requirements-dev.txt ]; then pip install -r Backend/app/requirements-dev.txt; fi

      - name: Run tests with coverage
        run: |
          pytest Backend/app/tests --cov=Backend/app --cov-report=xml

      - name: Upload coverage.xml artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml