name: Test SSH Connection to EC2

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Conexión SSH exitosa con EC2"
            hostname
            pwd
